version: "3.9"

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    container_name: iandu
    environment:
      POSTGRES_USER: iandu
      POSTGRES_PASSWORD: iandu
      POSTGRES_DB: iandu-db
    volumes:
      - ./data/pg:/data/postgres-iandu-db
