version: "3.9"

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    container_name: iandu
    environment:
      POSTGRES_USER: iandu
      POSTGRES_PASSWORD: iandu
      POSTGRES_DB: iandu-db
    volumes:
      - ./data/pg:/data/postgres-iandu-db

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "8081:16686"
      - "14268"
      - "14250"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "1888:1888"
      - "13133:13133"
      - "4317:4317"
      - "4318:4318"
      - "55679:55679"
    depends_on:
      - jaeger
    links:
      - jaeger
